-- Schema for a fresh database. History before the first production release is folded in here.
-- Flyway owns the schema. Hibernate does not create or alter it.
-- Entity tables have a BIGINT id and a public_id (UUID) for external references.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `admin_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(200) NOT NULL,
  `password_hash` varchar(100) NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `status` varchar(20) NOT NULL,
  `failed_login_attempts` int NOT NULL DEFAULT '0',
  `locked_until` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_user_public_id` (`public_id`),
  UNIQUE KEY `uq_admin_user_username` (`username`),
  UNIQUE KEY `uq_admin_user_email` (`email`),
  KEY `idx_admin_user_tenant` (`tenant_id`),
  CONSTRAINT `fk_admin_user_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `announcement` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `title` varchar(200) NOT NULL,
  `body` varchar(4000) NOT NULL,
  `published` tinyint(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_announcement_public_id` (`public_id`),
  KEY `idx_announcement_tenant` (`tenant_id`,`published`,`created_at`),
  CONSTRAINT `fk_announcement_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `attendance_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `device_user_id` varchar(64) DEFAULT NULL,
  `occurred_at` datetime(6) NOT NULL,
  `direction` varchar(8) NOT NULL,
  `method` varchar(32) DEFAULT NULL,
  `result` varchar(8) NOT NULL,
  `device_rec_no` bigint DEFAULT NULL,
  `fingerprint` varchar(120) NOT NULL,
  `deny_reason` varchar(64) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_att_public_id` (`public_id`),
  UNIQUE KEY `uq_att_dedupe` (`tenant_id`,`device_id`,`fingerprint`),
  KEY `idx_att_tenant_time` (`tenant_id`,`occurred_at`),
  KEY `idx_att_member` (`member_id`),
  KEY `fk_att_device` (`device_id`),
  CONSTRAINT `fk_att_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_att_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_att_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `attendance_sync_cursor` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `last_rec_no` bigint DEFAULT NULL,
  `last_event_at` datetime(6) DEFAULT NULL,
  `reconciliation_required` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_cursor_public_id` (`public_id`),
  UNIQUE KEY `uq_cursor_device` (`device_id`),
  KEY `fk_cursor_tenant` (`tenant_id`),
  CONSTRAINT `fk_cursor_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_cursor_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint DEFAULT NULL,
  `actor_user_id` bigint DEFAULT NULL,
  `actor_username` varchar(100) DEFAULT NULL,
  `action` varchar(80) NOT NULL,
  `resource_type` varchar(80) DEFAULT NULL,
  `resource_id` varchar(80) DEFAULT NULL,
  `result` varchar(20) NOT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `user_agent` varchar(256) DEFAULT NULL,
  `correlation_id` varchar(36) DEFAULT NULL,
  `details` text,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_audit_log_public_id` (`public_id`),
  KEY `idx_audit_log_tenant_time` (`tenant_id`,`created_at`),
  KEY `idx_audit_log_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `desired_member` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `revision` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `present_on_reader` tinyint(1) NOT NULL,
  `reader_name` varchar(31) NOT NULL,
  `reader_name_ex` varchar(127) DEFAULT NULL,
  `user_status` int NOT NULL,
  `valid_from` varchar(40) NOT NULL,
  `valid_to` varchar(40) NOT NULL,
  `authority` varchar(32) NOT NULL,
  `door_num` int NOT NULL,
  `time_section_num` int NOT NULL,
  `face_sha256` char(64) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `observed_face_sha256` char(64) DEFAULT NULL,
  `keep_device_user_id` tinyint(1) NOT NULL DEFAULT '0',
  `face_present` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_desired_member_public` (`public_id`),
  UNIQUE KEY `uq_desired_member_device_member` (`device_id`,`member_id`),
  KEY `idx_desired_member_revision` (`device_id`,`revision`),
  KEY `fk_desired_member_tenant` (`tenant_id`),
  KEY `fk_desired_member_member` (`member_id`),
  CONSTRAINT `fk_desired_member_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_desired_member_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_desired_member_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `name` varchar(120) NOT NULL,
  `gateway_id` bigint DEFAULT NULL,
  `role` varchar(16) NOT NULL,
  `host` varchar(120) DEFAULT NULL,
  `port` int DEFAULT NULL,
  `model` varchar(80) DEFAULT NULL,
  `serial_number` varchar(80) DEFAULT NULL,
  `firmware` varchar(80) DEFAULT NULL,
  `connection_state` varchar(16) NOT NULL,
  `last_seen_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `roster_digest` varchar(80) DEFAULT NULL,
  `roster_compared_at` datetime(6) DEFAULT NULL,
  `roster_trusted_empty` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_device_public_id` (`public_id`),
  KEY `idx_device_tenant` (`tenant_id`),
  KEY `idx_device_gateway` (`gateway_id`),
  CONSTRAINT `fk_device_gateway` FOREIGN KEY (`gateway_id`) REFERENCES `gateway` (`id`),
  CONSTRAINT `fk_device_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_observed_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `reader_name` varchar(127) DEFAULT NULL,
  `reader_name_ex` varchar(127) DEFAULT NULL,
  `user_status` int NOT NULL,
  `valid_from` varchar(40) DEFAULT NULL,
  `valid_to` varchar(40) DEFAULT NULL,
  `authority` varchar(32) DEFAULT NULL,
  `face_sha256` varchar(64) DEFAULT NULL,
  `observed_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_observed_user_public` (`public_id`),
  UNIQUE KEY `uq_observed_user_device` (`device_id`,`device_user_id`),
  KEY `fk_observed_user_tenant` (`tenant_id`),
  CONSTRAINT `fk_observed_user_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_observed_user_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_reader_baseline` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `reader_name` varchar(127) DEFAULT NULL,
  `reader_name_ex` varchar(127) DEFAULT NULL,
  `user_status` int NOT NULL,
  `valid_from` varchar(40) DEFAULT NULL,
  `valid_to` varchar(40) DEFAULT NULL,
  `authority` varchar(32) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_reader_baseline_public` (`public_id`),
  UNIQUE KEY `uq_reader_baseline_device` (`device_id`,`device_user_id`),
  KEY `fk_reader_baseline_tenant` (`tenant_id`),
  CONSTRAINT `fk_reader_baseline_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_reader_baseline_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_review_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `baseline_name` varchar(127) DEFAULT NULL,
  `baseline_name_ex` varchar(127) DEFAULT NULL,
  `baseline_authority` varchar(32) DEFAULT NULL,
  `server_name` varchar(127) DEFAULT NULL,
  `server_name_ex` varchar(127) DEFAULT NULL,
  `server_authority` varchar(32) DEFAULT NULL,
  `reader_name` varchar(127) DEFAULT NULL,
  `reader_name_ex` varchar(127) DEFAULT NULL,
  `reader_authority` varchar(32) DEFAULT NULL,
  `observed_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `reader_absent` tinyint(1) NOT NULL DEFAULT '0',
  `decision` varchar(32) DEFAULT NULL,
  `actor` varchar(100) DEFAULT NULL,
  `prior_state` varchar(255) DEFAULT NULL,
  `chosen_state` varchar(255) DEFAULT NULL,
  `decision_revision` bigint DEFAULT NULL,
  `verification_error` varchar(255) DEFAULT NULL,
  `resolved` tinyint(1) NOT NULL DEFAULT '0',
  `bootstrap_run_id` char(36) DEFAULT NULL,
  `baseline_valid_from` varchar(40) DEFAULT NULL,
  `baseline_valid_to` varchar(40) DEFAULT NULL,
  `server_valid_from` varchar(40) DEFAULT NULL,
  `server_valid_to` varchar(40) DEFAULT NULL,
  `reader_valid_from` varchar(40) DEFAULT NULL,
  `reader_valid_to` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_review_item_public` (`public_id`),
  UNIQUE KEY `uq_review_item_device_user` (`device_id`,`device_user_id`),
  KEY `fk_review_item_tenant` (`tenant_id`),
  KEY `fk_review_item_member` (`member_id`),
  CONSTRAINT `fk_review_item_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_review_item_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_review_item_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_review_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `review_item_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `reader_name` varchar(127) DEFAULT NULL,
  `reader_name_ex` varchar(127) DEFAULT NULL,
  `reader_authority` varchar(32) DEFAULT NULL,
  `observed_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `reader_valid_from` varchar(40) DEFAULT NULL,
  `reader_valid_to` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_review_snapshot_public` (`public_id`),
  UNIQUE KEY `uq_review_snapshot_reader` (`review_item_id`,`device_id`),
  KEY `fk_review_snapshot_tenant` (`tenant_id`),
  KEY `fk_review_snapshot_device` (`device_id`),
  CONSTRAINT `fk_review_snapshot_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_review_snapshot_item` FOREIGN KEY (`review_item_id`) REFERENCES `device_review_item` (`id`),
  CONSTRAINT `fk_review_snapshot_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_sync_command` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `member_id` bigint DEFAULT NULL,
  `membership_id` bigint DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `payload` text,
  `state` varchar(16) NOT NULL,
  `attempt_count` int NOT NULL,
  `max_attempts` int NOT NULL,
  `next_attempt_at` datetime(6) NOT NULL,
  `last_error` varchar(500) DEFAULT NULL,
  `correlation_id` char(36) NOT NULL,
  `dispatched_at` datetime(6) DEFAULT NULL,
  `acknowledged_at` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dsc_public_id` (`public_id`),
  UNIQUE KEY `uq_dsc_correlation` (`correlation_id`),
  KEY `idx_dsc_tenant` (`tenant_id`),
  KEY `idx_dsc_device` (`device_id`),
  KEY `idx_dsc_due` (`state`,`next_attempt_at`),
  KEY `fk_dsc_member` (`member_id`),
  KEY `fk_dsc_membership` (`membership_id`),
  CONSTRAINT `fk_dsc_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_dsc_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_dsc_membership` FOREIGN KEY (`membership_id`) REFERENCES `membership` (`id`),
  CONSTRAINT `fk_dsc_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `device_user_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `name` varchar(120) DEFAULT NULL,
  `frozen` tinyint(1) NOT NULL DEFAULT '0',
  `valid_from` date DEFAULT NULL,
  `valid_to` date DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_device_user_snapshot_public_id` (`public_id`),
  UNIQUE KEY `uq_device_user_snapshot_device_user` (`device_id`,`device_user_id`),
  KEY `idx_device_user_snapshot_tenant` (`tenant_id`),
  KEY `idx_device_user_snapshot_device` (`device_id`),
  CONSTRAINT `fk_device_user_snapshot_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_device_user_snapshot_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `enquiry` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `name` varchar(150) NOT NULL,
  `email` varchar(200) NOT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `message` varchar(2000) NOT NULL,
  `plan_interest` varchar(120) DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `staff_notes` varchar(1000) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_enquiry_public_id` (`public_id`),
  KEY `idx_enquiry_tenant_status` (`tenant_id`,`status`,`created_at`),
  CONSTRAINT `fk_enquiry_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gateway` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `name` varchar(120) NOT NULL,
  `status` varchar(16) NOT NULL,
  `last_heartbeat_at` datetime(6) DEFAULT NULL,
  `last_registered_at` datetime(6) DEFAULT NULL,
  `agent_version` varchar(40) DEFAULT NULL,
  `token_hash` char(64) NOT NULL,
  `enrollment_token_hash` char(64) DEFAULT NULL,
  `enrollment_expires_at` datetime(6) DEFAULT NULL,
  `enrollment_consumed_at` datetime(6) DEFAULT NULL,
  `token_expires_at` datetime(6) DEFAULT NULL,
  `next_token_hash` char(64) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_gateway_public_id` (`public_id`),
  UNIQUE KEY `uq_gateway_token_hash` (`token_hash`),
  UNIQUE KEY `uq_gateway_tenant` (`tenant_id`),
  UNIQUE KEY `uq_gateway_enrollment_token_hash` (`enrollment_token_hash`),
  UNIQUE KEY `uq_gateway_next_token_hash` (`next_token_hash`),
  CONSTRAINT `fk_gateway_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gateway_face_upload` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `gateway_id` bigint NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `sha256` char(64) NOT NULL,
  `size_bytes` int NOT NULL,
  `consumed` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_gateway_face_upload_public_id` (`public_id`),
  KEY `idx_gateway_face_upload_created` (`created_at`),
  KEY `fk_gfu_tenant` (`tenant_id`),
  KEY `fk_gfu_gateway` (`gateway_id`),
  CONSTRAINT `fk_gfu_gateway` FOREIGN KEY (`gateway_id`) REFERENCES `gateway` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_gfu_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gateway_message_dedupe` (
  `message_id` char(36) NOT NULL,
  `gateway_id` bigint DEFAULT NULL,
  `received_at` datetime(6) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  PRIMARY KEY (`message_id`),
  KEY `idx_gmd_expires` (`expires_at`),
  KEY `fk_gmd_gateway` (`gateway_id`),
  CONSTRAINT `fk_gmd_gateway` FOREIGN KEY (`gateway_id`) REFERENCES `gateway` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `gym_profile` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `tagline` varchar(200) DEFAULT NULL,
  `about` varchar(4000) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `address` varchar(300) DEFAULT NULL,
  `hours` varchar(300) DEFAULT NULL,
  `display_name` varchar(150) DEFAULT NULL,
  `logo_url` varchar(500) DEFAULT NULL,
  `hero_image_url` varchar(500) DEFAULT NULL,
  `training_image_url` varchar(500) DEFAULT NULL,
  `facilities_image_url` varchar(500) DEFAULT NULL,
  `section_training_title` varchar(120) DEFAULT NULL,
  `section_training_body` varchar(1000) DEFAULT NULL,
  `section_facilities_title` varchar(120) DEFAULT NULL,
  `section_facilities_body` varchar(1000) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_gym_profile_public_id` (`public_id`),
  UNIQUE KEY `uq_gym_profile_tenant` (`tenant_id`),
  CONSTRAINT `fk_gym_profile_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `member` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `member_code` varchar(32) NOT NULL,
  `first_name` varchar(80) NOT NULL,
  `last_name` varchar(80) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `phone` varchar(32) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` varchar(16) NOT NULL,
  `status` varchar(16) NOT NULL,
  `joined_on` date NOT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `creation_source` varchar(16) NOT NULL DEFAULT 'MANUAL',
  `profile_changed_at` datetime(6) DEFAULT NULL,
  `access_changed_at` datetime(6) DEFAULT NULL,
  `face_changed_at` datetime(6) DEFAULT NULL,
  `device_valid_from` date DEFAULT NULL,
  `device_valid_to` date DEFAULT NULL,
  `device_enabled` tinyint(1) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `device_authority` varchar(32) NOT NULL DEFAULT 'USER',
  `serial_number` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_member_public_id` (`public_id`),
  UNIQUE KEY `uq_member_tenant_code` (`tenant_id`,`member_code`),
  UNIQUE KEY `uq_member_tenant_serial` (`tenant_id`,`serial_number`),
  KEY `idx_member_tenant` (`tenant_id`),
  KEY `idx_member_phone` (`phone`),
  CONSTRAINT `fk_member_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `member_device_mapping` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `enrollment_status` varchar(20) NOT NULL,
  `sync_state` varchar(16) NOT NULL,
  `enrolled_at` datetime(6) DEFAULT NULL,
  `face_version_synced` int DEFAULT NULL,
  `face_sync_state` varchar(16) NOT NULL DEFAULT 'NOT_SYNCED',
  `face_last_error` varchar(500) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `pending_device_user_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_mdm_public_id` (`public_id`),
  UNIQUE KEY `uq_mdm_device_user` (`device_id`,`device_user_id`),
  UNIQUE KEY `uq_mdm_device_member` (`device_id`,`member_id`),
  KEY `idx_mdm_tenant` (`tenant_id`),
  KEY `idx_mdm_member` (`member_id`),
  CONSTRAINT `fk_mdm_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_mdm_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_mdm_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `member_face` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `sha256` char(64) NOT NULL,
  `face_version` int NOT NULL,
  `size_bytes` int NOT NULL,
  `source` varchar(16) NOT NULL,
  `source_device_id` bigint DEFAULT NULL,
  `changed_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_member_face_public_id` (`public_id`),
  UNIQUE KEY `uq_member_face_member` (`member_id`),
  KEY `idx_member_face_tenant` (`tenant_id`),
  KEY `fk_member_face_device` (`source_device_id`),
  CONSTRAINT `fk_member_face_device` FOREIGN KEY (`source_device_id`) REFERENCES `device` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_member_face_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_member_face_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `membership` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `plan_id` bigint DEFAULT NULL,
  `plan_name` varchar(120) NOT NULL,
  `price` decimal(12,2) NOT NULL,
  `currency` char(3) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `end_date_inferred` tinyint(1) NOT NULL DEFAULT '0',
  `status` varchar(16) NOT NULL,
  `payment_status` varchar(16) NOT NULL,
  `amount_paid` decimal(12,2) NOT NULL,
  `device_sync_state` varchar(16) NOT NULL,
  `frozen_on` date DEFAULT NULL,
  `freeze_days_accumulated` int NOT NULL,
  `cancelled_on` date DEFAULT NULL,
  `cancel_reason` varchar(300) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  `discount_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `discount_approved_by_user_id` bigint DEFAULT NULL,
  `discount_approved_by_username` varchar(100) DEFAULT NULL,
  `discount_approved_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_membership_public_id` (`public_id`),
  KEY `idx_membership_tenant` (`tenant_id`),
  KEY `idx_membership_member` (`member_id`),
  KEY `idx_membership_end_date` (`end_date`),
  KEY `fk_membership_plan` (`plan_id`),
  KEY `idx_membership_deleted` (`deleted`),
  CONSTRAINT `fk_membership_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_membership_plan` FOREIGN KEY (`plan_id`) REFERENCES `membership_plan` (`id`),
  CONSTRAINT `fk_membership_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `membership_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `name` varchar(120) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `price` decimal(12,2) NOT NULL,
  `currency` char(3) NOT NULL,
  `duration_days` int NOT NULL,
  `status` varchar(20) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_plan_public_id` (`public_id`),
  KEY `idx_plan_tenant` (`tenant_id`),
  CONSTRAINT `fk_plan_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `template_key` varchar(64) NOT NULL,
  `channel` varchar(16) NOT NULL,
  `subject` varchar(200) DEFAULT NULL,
  `body` varchar(4000) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_notification_template_public_id` (`public_id`),
  UNIQUE KEY `uq_notification_template_key` (`tenant_id`,`template_key`,`channel`),
  CONSTRAINT `fk_notification_template_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `outbound_notification` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `channel` varchar(16) NOT NULL,
  `template_key` varchar(64) DEFAULT NULL,
  `recipient` varchar(200) NOT NULL,
  `subject` varchar(200) DEFAULT NULL,
  `body` varchar(4000) NOT NULL,
  `status` varchar(16) NOT NULL,
  `attempt_count` int NOT NULL,
  `last_error` varchar(500) DEFAULT NULL,
  `sent_at` datetime(6) DEFAULT NULL,
  `member_id` bigint DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_outbound_notification_public_id` (`public_id`),
  KEY `idx_outbound_notification_tenant` (`tenant_id`,`created_at`),
  CONSTRAINT `fk_outbound_notification_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `member_id` bigint NOT NULL,
  `membership_id` bigint DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `currency` char(3) NOT NULL,
  `method` varchar(20) NOT NULL,
  `status` varchar(16) NOT NULL,
  `reference` varchar(120) DEFAULT NULL,
  `paid_on` date NOT NULL,
  `received_by_user_id` bigint DEFAULT NULL,
  `received_by_username` varchar(100) DEFAULT NULL,
  `notes` varchar(500) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payment_public_id` (`public_id`),
  KEY `idx_payment_tenant` (`tenant_id`),
  KEY `idx_payment_member` (`member_id`),
  KEY `idx_payment_membership` (`membership_id`),
  CONSTRAINT `fk_payment_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_payment_membership` FOREIGN KEY (`membership_id`) REFERENCES `membership` (`id`),
  CONSTRAINT `fk_payment_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pending_enrollment` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `review_status` varchar(16) NOT NULL,
  `observed_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  `decision` varchar(32) DEFAULT NULL,
  `actor` varchar(100) DEFAULT NULL,
  `prior_state` varchar(255) DEFAULT NULL,
  `chosen_state` varchar(255) DEFAULT NULL,
  `decision_revision` bigint DEFAULT NULL,
  `verification_error` varchar(255) DEFAULT NULL,
  `resolved` tinyint(1) NOT NULL DEFAULT '0',
  `bootstrap_run_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_pending_enrollment_public` (`public_id`),
  UNIQUE KEY `uq_pending_enrollment_device` (`device_id`,`device_user_id`),
  KEY `fk_pending_enrollment_tenant` (`tenant_id`),
  CONSTRAINT `fk_pending_enrollment_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_pending_enrollment_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `permission` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `name` varchar(64) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_permission_public_id` (`public_id`),
  UNIQUE KEY `uq_permission_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reader_blocked_user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_blocked_public` (`public_id`),
  UNIQUE KEY `uq_blocked_device_user` (`device_id`,`device_user_id`),
  KEY `fk_blocked_tenant` (`tenant_id`),
  CONSTRAINT `fk_blocked_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_blocked_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reader_revision` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `desired_revision` bigint NOT NULL,
  `applied_revision` bigint NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_reader_revision_public` (`public_id`),
  UNIQUE KEY `uq_reader_revision_device` (`device_id`),
  KEY `fk_reader_revision_tenant` (`tenant_id`),
  CONSTRAINT `fk_reader_revision_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_reader_revision_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reconciliation_conflict` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `device_user_id` varchar(64) NOT NULL,
  `conflict_type` varchar(32) NOT NULL,
  `details` text,
  `status` varchar(16) NOT NULL,
  `resolved_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_rc_public_id` (`public_id`),
  KEY `idx_rc_tenant_device` (`tenant_id`,`device_id`,`status`),
  KEY `fk_rc_device` (`device_id`),
  CONSTRAINT `fk_rc_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_rc_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `refresh_token` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `user_id` bigint NOT NULL,
  `token_hash` char(64) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `revoked` tinyint(1) NOT NULL DEFAULT '0',
  `replaced_by` char(36) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_refresh_token_public_id` (`public_id`),
  UNIQUE KEY `uq_refresh_token_hash` (`token_hash`),
  KEY `idx_refresh_token_user` (`user_id`),
  CONSTRAINT `fk_refresh_token_user` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `name` varchar(64) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `tenant_id` bigint DEFAULT NULL,
  `is_system` tinyint(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_role_public_id` (`public_id`),
  UNIQUE KEY `uq_role_name_tenant` (`name`,`tenant_id`),
  KEY `fk_role_tenant` (`tenant_id`),
  CONSTRAINT `fk_role_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role_permission` (
  `role_id` bigint NOT NULL,
  `permission_id` bigint NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `fk_rp_permission` (`permission_id`),
  CONSTRAINT `fk_rp_permission` FOREIGN KEY (`permission_id`) REFERENCES `permission` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_rp_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `security_event` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `tenant_id` bigint NOT NULL,
  `device_id` bigint DEFAULT NULL,
  `type` varchar(48) NOT NULL,
  `occurred_at` datetime(6) NOT NULL,
  `details` text,
  `acknowledged` tinyint(1) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sec_public_id` (`public_id`),
  KEY `idx_sec_tenant_time` (`tenant_id`,`occurred_at`),
  KEY `fk_sec_device` (`device_id`),
  CONSTRAINT `fk_sec_device` FOREIGN KEY (`device_id`) REFERENCES `device` (`id`),
  CONSTRAINT `fk_sec_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tenant` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `public_id` char(36) NOT NULL,
  `name` varchar(150) NOT NULL,
  `slug` varchar(80) NOT NULL,
  `status` varchar(20) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `version` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tenant_public_id` (`public_id`),
  UNIQUE KEY `uq_tenant_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_role` (
  `user_id` bigint NOT NULL,
  `role_id` bigint NOT NULL,
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `fk_ur_role` (`role_id`),
  CONSTRAINT `fk_ur_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ur_user` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS = 1;

