-- V9: one review item for a mapped reader edit. It keeps the server, reader, and baseline names.

CREATE TABLE device_reader_baseline (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    public_id       CHAR(36)     NOT NULL,
    tenant_id       BIGINT       NOT NULL,
    device_id       BIGINT       NOT NULL,
    device_user_id  VARCHAR(64)  NOT NULL,
    reader_name     VARCHAR(127),
    reader_name_ex  VARCHAR(127),
    user_status     INT          NOT NULL,
    valid_from      VARCHAR(40),
    valid_to        VARCHAR(40),
    authority       VARCHAR(32),
    created_at      DATETIME(6)  NOT NULL,
    updated_at      DATETIME(6)  NOT NULL,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    version         BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_reader_baseline_public (public_id),
    UNIQUE KEY uq_reader_baseline_device (device_id, device_user_id),
    CONSTRAINT fk_reader_baseline_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_reader_baseline_device FOREIGN KEY (device_id) REFERENCES device (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE device_review_item (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    public_id           CHAR(36)     NOT NULL,
    tenant_id           BIGINT       NOT NULL,
    device_id           BIGINT       NOT NULL,
    member_id           BIGINT       NOT NULL,
    device_user_id      VARCHAR(64)  NOT NULL,
    baseline_name       VARCHAR(127),
    baseline_name_ex    VARCHAR(127),
    baseline_authority  VARCHAR(32),
    server_name         VARCHAR(127),
    server_name_ex      VARCHAR(127),
    server_authority    VARCHAR(32),
    reader_name         VARCHAR(127),
    reader_name_ex      VARCHAR(127),
    reader_authority    VARCHAR(32),
    observed_at         DATETIME(6)  NOT NULL,
    created_at          DATETIME(6)  NOT NULL,
    updated_at          DATETIME(6)  NOT NULL,
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    version             BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_review_item_public (public_id),
    UNIQUE KEY uq_review_item_device_user (device_id, device_user_id),
    CONSTRAINT fk_review_item_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_review_item_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT fk_review_item_member FOREIGN KEY (member_id) REFERENCES member (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
