-- Phase 2: membership plans, members, memberships, and payments. All tenant-scoped.

CREATE TABLE membership_plan (
    id            BIGINT        NOT NULL AUTO_INCREMENT,
    public_id     CHAR(36)      NOT NULL,
    tenant_id     BIGINT        NOT NULL,
    name          VARCHAR(120)  NOT NULL,
    description   VARCHAR(500),
    price         DECIMAL(12,2) NOT NULL,
    currency      CHAR(3)       NOT NULL,
    duration_days INT           NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    created_at    DATETIME(6)   NOT NULL,
    updated_at    DATETIME(6)   NOT NULL,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    version       BIGINT        NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_plan_public_id (public_id),
    KEY idx_plan_tenant (tenant_id),
    CONSTRAINT fk_plan_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE member (
    id            BIGINT       NOT NULL AUTO_INCREMENT,
    public_id     CHAR(36)     NOT NULL,
    tenant_id     BIGINT       NOT NULL,
    member_code   VARCHAR(32)  NOT NULL,
    first_name    VARCHAR(80)  NOT NULL,
    last_name     VARCHAR(80),
    email         VARCHAR(200),
    phone         VARCHAR(32),
    date_of_birth DATE,
    gender        VARCHAR(16)  NOT NULL,
    status        VARCHAR(16)  NOT NULL,
    joined_on     DATE         NOT NULL,
    notes         VARCHAR(1000),
    created_at    DATETIME(6)  NOT NULL,
    updated_at    DATETIME(6)  NOT NULL,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    version       BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_member_public_id (public_id),
    UNIQUE KEY uq_member_tenant_code (tenant_id, member_code),
    KEY idx_member_tenant (tenant_id),
    KEY idx_member_phone (phone),
    CONSTRAINT fk_member_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE membership (
    id                      BIGINT        NOT NULL AUTO_INCREMENT,
    public_id               CHAR(36)      NOT NULL,
    tenant_id               BIGINT        NOT NULL,
    member_id               BIGINT        NOT NULL,
    plan_id                 BIGINT,
    plan_name               VARCHAR(120)  NOT NULL,
    price                   DECIMAL(12,2) NOT NULL,
    currency                CHAR(3)       NOT NULL,
    start_date              DATE          NOT NULL,
    end_date                DATE          NOT NULL,
    status                  VARCHAR(16)   NOT NULL,
    payment_status          VARCHAR(16)   NOT NULL,
    amount_paid             DECIMAL(12,2) NOT NULL,
    device_sync_state       VARCHAR(16)   NOT NULL,
    frozen_on               DATE,
    freeze_days_accumulated INT           NOT NULL,
    cancelled_on            DATE,
    cancel_reason           VARCHAR(300),
    created_at              DATETIME(6)   NOT NULL,
    updated_at              DATETIME(6)   NOT NULL,
    created_by              VARCHAR(100),
    updated_by              VARCHAR(100),
    version                 BIGINT        NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_membership_public_id (public_id),
    KEY idx_membership_tenant (tenant_id),
    KEY idx_membership_member (member_id),
    KEY idx_membership_end_date (end_date),
    CONSTRAINT fk_membership_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_membership_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_membership_plan FOREIGN KEY (plan_id) REFERENCES membership_plan (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE payment (
    id                   BIGINT        NOT NULL AUTO_INCREMENT,
    public_id            CHAR(36)      NOT NULL,
    tenant_id            BIGINT        NOT NULL,
    member_id            BIGINT        NOT NULL,
    membership_id        BIGINT,
    amount               DECIMAL(12,2) NOT NULL,
    currency             CHAR(3)       NOT NULL,
    method               VARCHAR(20)   NOT NULL,
    status               VARCHAR(16)   NOT NULL,
    reference            VARCHAR(120),
    paid_on              DATE          NOT NULL,
    received_by_user_id  BIGINT,
    received_by_username VARCHAR(100),
    notes                VARCHAR(500),
    created_at           DATETIME(6)   NOT NULL,
    updated_at           DATETIME(6)   NOT NULL,
    created_by           VARCHAR(100),
    updated_by           VARCHAR(100),
    version              BIGINT        NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_payment_public_id (public_id),
    KEY idx_payment_tenant (tenant_id),
    KEY idx_payment_member (member_id),
    KEY idx_payment_membership (membership_id),
    CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_payment_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_payment_membership FOREIGN KEY (membership_id) REFERENCES membership (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
