-- Phase 3: device integration domain — gateways, devices, member-device mappings, the sync outbox,
-- attendance events + watermarks, and security events. All tenant-scoped. The backend stores no
-- device credentials (those live with the on-LAN gateway).

CREATE TABLE gateway (
    id                 BIGINT       NOT NULL AUTO_INCREMENT,
    public_id          CHAR(36)     NOT NULL,
    tenant_id          BIGINT       NOT NULL,
    name               VARCHAR(120) NOT NULL,
    status             VARCHAR(16)  NOT NULL,
    last_heartbeat_at  DATETIME(6),
    last_registered_at DATETIME(6),
    agent_version      VARCHAR(40),
    token_hash         CHAR(64)     NOT NULL,
    created_at         DATETIME(6)  NOT NULL,
    updated_at         DATETIME(6)  NOT NULL,
    created_by         VARCHAR(100),
    updated_by         VARCHAR(100),
    version            BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_gateway_public_id (public_id),
    UNIQUE KEY uq_gateway_token_hash (token_hash),
    KEY idx_gateway_tenant (tenant_id),
    CONSTRAINT fk_gateway_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE device (
    id               BIGINT       NOT NULL AUTO_INCREMENT,
    public_id        CHAR(36)     NOT NULL,
    tenant_id        BIGINT       NOT NULL,
    name             VARCHAR(120) NOT NULL,
    gateway_id       BIGINT,
    role             VARCHAR(16)  NOT NULL,
    host             VARCHAR(120),
    port             INT,
    model            VARCHAR(80),
    serial_number    VARCHAR(80),
    firmware         VARCHAR(80),
    connection_state VARCHAR(16)  NOT NULL,
    last_seen_at     DATETIME(6),
    created_at       DATETIME(6)  NOT NULL,
    updated_at       DATETIME(6)  NOT NULL,
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    version          BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_device_public_id (public_id),
    KEY idx_device_tenant (tenant_id),
    KEY idx_device_gateway (gateway_id),
    CONSTRAINT fk_device_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_device_gateway FOREIGN KEY (gateway_id) REFERENCES gateway (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE member_device_mapping (
    id                BIGINT       NOT NULL AUTO_INCREMENT,
    public_id         CHAR(36)     NOT NULL,
    tenant_id         BIGINT       NOT NULL,
    member_id         BIGINT       NOT NULL,
    device_id         BIGINT       NOT NULL,
    device_user_id    VARCHAR(64)  NOT NULL,
    enrollment_status VARCHAR(20)  NOT NULL,
    sync_state        VARCHAR(16)  NOT NULL,
    enrolled_at       DATETIME(6),
    created_at        DATETIME(6)  NOT NULL,
    updated_at        DATETIME(6)  NOT NULL,
    created_by        VARCHAR(100),
    updated_by        VARCHAR(100),
    version           BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_mdm_public_id (public_id),
    UNIQUE KEY uq_mdm_device_user (device_id, device_user_id),
    UNIQUE KEY uq_mdm_device_member (device_id, member_id),
    KEY idx_mdm_tenant (tenant_id),
    KEY idx_mdm_member (member_id),
    CONSTRAINT fk_mdm_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_mdm_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_mdm_device FOREIGN KEY (device_id) REFERENCES device (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE device_sync_command (
    id              BIGINT      NOT NULL AUTO_INCREMENT,
    public_id       CHAR(36)    NOT NULL,
    tenant_id       BIGINT      NOT NULL,
    device_id       BIGINT      NOT NULL,
    member_id       BIGINT,
    membership_id   BIGINT,
    type            VARCHAR(32) NOT NULL,
    payload         TEXT,
    state           VARCHAR(16) NOT NULL,
    attempt_count   INT         NOT NULL,
    max_attempts    INT         NOT NULL,
    next_attempt_at DATETIME(6) NOT NULL,
    last_error      VARCHAR(500),
    correlation_id  CHAR(36)    NOT NULL,
    dispatched_at   DATETIME(6),
    acknowledged_at DATETIME(6),
    completed_at    DATETIME(6),
    created_at      DATETIME(6) NOT NULL,
    updated_at      DATETIME(6) NOT NULL,
    created_by      VARCHAR(100),
    updated_by      VARCHAR(100),
    version         BIGINT      NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_dsc_public_id (public_id),
    UNIQUE KEY uq_dsc_correlation (correlation_id),
    KEY idx_dsc_tenant (tenant_id),
    KEY idx_dsc_device (device_id),
    KEY idx_dsc_due (state, next_attempt_at),
    CONSTRAINT fk_dsc_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_dsc_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT fk_dsc_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_dsc_membership FOREIGN KEY (membership_id) REFERENCES membership (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE attendance_event (
    id             BIGINT       NOT NULL AUTO_INCREMENT,
    public_id      CHAR(36)     NOT NULL,
    tenant_id      BIGINT       NOT NULL,
    device_id      BIGINT       NOT NULL,
    member_id      BIGINT,
    device_user_id VARCHAR(64),
    occurred_at    DATETIME(6)  NOT NULL,
    direction      VARCHAR(8)   NOT NULL,
    method         VARCHAR(32),
    result         VARCHAR(8)   NOT NULL,
    device_rec_no  BIGINT,
    fingerprint    VARCHAR(120) NOT NULL,
    created_at     DATETIME(6)  NOT NULL,
    updated_at     DATETIME(6)  NOT NULL,
    created_by     VARCHAR(100),
    updated_by     VARCHAR(100),
    version        BIGINT       NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_att_public_id (public_id),
    UNIQUE KEY uq_att_dedupe (tenant_id, device_id, fingerprint),
    KEY idx_att_tenant_time (tenant_id, occurred_at),
    KEY idx_att_member (member_id),
    CONSTRAINT fk_att_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_att_device FOREIGN KEY (device_id) REFERENCES device (id),
    CONSTRAINT fk_att_member FOREIGN KEY (member_id) REFERENCES member (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE attendance_sync_cursor (
    id            BIGINT      NOT NULL AUTO_INCREMENT,
    public_id     CHAR(36)    NOT NULL,
    tenant_id     BIGINT      NOT NULL,
    device_id     BIGINT      NOT NULL,
    last_rec_no   BIGINT,
    last_event_at DATETIME(6),
    created_at    DATETIME(6) NOT NULL,
    updated_at    DATETIME(6) NOT NULL,
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    version       BIGINT      NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_cursor_public_id (public_id),
    UNIQUE KEY uq_cursor_device (device_id),
    CONSTRAINT fk_cursor_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_cursor_device FOREIGN KEY (device_id) REFERENCES device (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE security_event (
    id           BIGINT      NOT NULL AUTO_INCREMENT,
    public_id    CHAR(36)    NOT NULL,
    tenant_id    BIGINT      NOT NULL,
    device_id    BIGINT,
    type         VARCHAR(48) NOT NULL,
    occurred_at  DATETIME(6) NOT NULL,
    details      TEXT,
    acknowledged BOOLEAN     NOT NULL,
    created_at   DATETIME(6) NOT NULL,
    updated_at   DATETIME(6) NOT NULL,
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    version      BIGINT      NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sec_public_id (public_id),
    KEY idx_sec_tenant_time (tenant_id, occurred_at),
    CONSTRAINT fk_sec_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id),
    CONSTRAINT fk_sec_device FOREIGN KEY (device_id) REFERENCES device (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
